* TODO managing bookmarks
** CRUD
for bookmarks and categories
** devel tools
figure out how to write this kind of application
write some cool macros ;-)
*** TODO integration of lisp and js code via ajax

** convenient input of categories
provide some autocompletion facility to speed things up
** explore UI possibilities
something Emacs like? could be very efficient, and would integrate well with conkeror
* TODO browser integration / synchronisation
perhaps an addon for chrome/chromium, maybe conkeror
this is mostly important for being able to add bookmarks from open tabs/windows
the other important function of bookmarks is being able to get completions of them in the address bar
** synchronisation / data transfer protocol
chromium exports its bookmarks in a JSON format, this could also be useful for importing data
** TODO import existing bookmarks
automatic tagging when things come from a hierarchy?
* TODO hierarchy computation
Just give tags to your bookmarks and let the computer figure out the hierarchy
Epiphany was doing that
** tuning if necessary
perhaps priorities for categories (to express generality of a tag)
** double entries
should we allow bookmarks to appear twice in the hierarchy? Maybe in an alternative browsing mode -- "filtering view" or something
* TODO multi user capabilities
** sharing of bookmarks?
** possible issues
global vs local names, category assignment
* TODO authentication
even if the system stays single user, it needs some way to protect the data (at the very least against changes)
